services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roundup-games
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - app_storage:/var/www/html/storage
    ports:
      - "8199:8080"
    networks:
      - roundup

volumes:
  app_storage:

networks:
  roundup:
    driver: bridge
