#!/usr/bin/env php
<?php

/**
 * Generate a Larastan-compatible schema file from the PostgreSQL schema dump.
 *
 * Problem: Larastan discovers model columns by parsing schema files in
 * database/schema/. Its SQL parser cannot handle the PostgreSQL dump format
 * (psql meta-commands like \restrict cause fatal parse errors; PostgreSQL-
 * specific types like uuid, jsonb, bytea are rejected).
 *
 * Solution: extract only the CREATE TABLE statements from the runtime dump
 * and map problematic types to parser-friendly equivalents. The type mapping
 * is safe for static analysis — Larastan only needs column names and broad
 * type categories; the exact PostgreSQL storage type is irrelevant.
 *
 * This file is consumed ONLY by Larastan for static analysis. It is never
 * loaded at runtime (psql loads pgsql-schema.sql for that).
 *
 * Usage:  php scripts/generate-larastan-schema.php
 * Run after re-squashing (schema:dump --prune) to regenerate.
 */
$dumpPath = __DIR__.'/../database/schema/pgsql-schema.sql';
$outputPath = __DIR__.'/../database/schema/larastan-schema.sql';

if (! file_exists($dumpPath)) {
    fwrite(STDERR, "Error: {$dumpPath} not found. Run schema:dump first.\n");
    exit(1);
}

$sql = file_get_contents($dumpPath);

// Extract only CREATE TABLE statements — the DDL Larastan needs for column
// discovery. Everything else (COPY data, ALTER TABLE constraints, triggers,
// functions, sequences, psql meta-commands) is irrelevant.
preg_match_all('/^(CREATE TABLE [^;]+;)\s*$/ms', $sql, $matches);

if (empty($matches[1])) {
    fwrite(STDERR, "Error: no CREATE TABLE statements found in {$dumpPath}\n");
    exit(1);
}

$typeMap = [
    // Types the iamcal SQL parser rejects entirely (causes a fatal parse error).
    // Match only in TYPE position: preceded by a word char + whitespace
    // (i.e. follows a column name), NOT when the word IS a column name.
    '/(\w)\s+uuid\b/i' => '$1 varchar',
    '/(\w)\s+jsonb\b/i' => '$1 json',
    '/(\w)\s+bytea\b/i' => '$1 text',
    // Types the parser accepts but MySqlDataTypeToPhpTypeConverter doesn't
    // recognise (falls through to 'mixed', causing type errors):
    '/\bcharacter varying\b/i' => 'varchar',
    '/\btimestamp(\(\d+\))? without time zone\b/i' => 'timestamp',
    '/\btime(\(\d+\))? without time zone\b/i' => 'time',
];

$output = "-- Auto-generated by scripts/generate-larastan-schema.php\n";
$output .= "-- DO NOT EDIT — regenerate after re-squashing migrations.\n";
$output .= "-- Consumed by Larastan for model property discovery only.\n";
$output .= "-- NOT loaded at runtime — psql loads pgsql-schema.sql for that.\n\n";

foreach ($matches[1] as $createTable) {
    $mapped = preg_replace(array_keys($typeMap), array_values($typeMap), $createTable);

    // Ensure PostgreSQL nullable-by-default semantics are preserved.
    // The iamcal SQL parser defaults to NOT NULL when nullability is
    // unspecified (MySQL convention), but PostgreSQL defaults to nullable.
    // Without explicit NULL on nullable columns, Larastan reports false
    // positives (defensive null checks flagged as redundant on columns that
    // are genuinely nullable). We add explicit NULL to every column line
    // that doesn't already have a NULL/NOT NULL marker.
    $mapped = preg_replace_callback(
        '/^(\s+[a-z_]+\s+.+?)(\s*,?\s*)$/mi',
        static function (array $m): string {
            // Skip constraint definitions (CONSTRAINT, PRIMARY KEY, etc.)
            if (preg_match('/^(CONSTRAINT|PRIMARY|UNIQUE|FOREIGN|CHECK|KEY)\b/i', trim($m[1]))) {
                return $m[0];
            }
            // Skip if the column already has an explicit NULL/NOT NULL marker
            if (preg_match('/\bNULL\b/i', $m[1])) {
                return $m[0];
            }

            return $m[1].' NULL'.$m[2];
        },
        $mapped
    );

    $output .= $mapped."\n\n";
}

$bytes = file_put_contents($outputPath, $output);
$tableCount = count($matches[1]);

echo "Generated {$outputPath}\n";
echo "  Tables: {$tableCount}\n";
echo '  Size:   '.number_format($bytes)." bytes\n";
echo "  Type mappings: uuid→varchar, jsonb→json, bytea→text,\n";
echo "                 character varying→varchar, timestamp(0)→timestamp, time(0)→time\n";
echo "  Nullable: explicit NULL added (PostgreSQL defaults to nullable)\n";
