#!/usr/bin/env php
<?php

use Larastan\Larastan\SQL\IamcalSqlParser;

/**
 * Generate a Larastan-compatible schema file from the PostgreSQL schema dump.
 *
 * Problem: Larastan discovers model columns by parsing schema files in
 * database/schema/. Its SQL parser cannot handle the PostgreSQL dump format
 * (psql meta-commands like \restrict cause fatal parse errors; PostgreSQL-
 * specific types like uuid, jsonb, bytea are rejected).
 *
 * Solution: extract only the CREATE TABLE statements from the runtime dump
 * and map problematic types to parser-friendly equivalents. The type mapping
 * is safe for static analysis — Larastan only needs column names and broad
 * type categories; the exact PostgreSQL storage type is irrelevant.
 *
 * This file is consumed ONLY by Larastan for static analysis. It is never
 * loaded at runtime (psql loads pgsql-schema.sql for that).
 *
 * Usage:  php scripts/generate-larastan-schema.php
 * Run after re-squashing (schema:dump --prune) to regenerate.
 */
$dumpPath = __DIR__.'/../database/schema/pgsql-schema.sql';
$outputPath = __DIR__.'/../database/schema/larastan-schema.sql';

if (! file_exists($dumpPath)) {
    fwrite(STDERR, "Error: {$dumpPath} not found. Run schema:dump first.\n");
    exit(1);
}

$sql = file_get_contents($dumpPath);

// Extract only CREATE TABLE statements — the DDL Larastan needs for column
// discovery. Everything else (COPY data, ALTER TABLE constraints, triggers,
// functions, sequences, psql meta-commands) is irrelevant.
preg_match_all('/^(CREATE TABLE [^;]+;)\s*$/ms', $sql, $matches);

if (empty($matches[1])) {
    fwrite(STDERR, "Error: no CREATE TABLE statements found in {$dumpPath}\n");
    exit(1);
}

$typeMap = [
    // Types the iamcal SQL parser rejects entirely (causes a fatal parse error).
    // Match only in TYPE position: preceded by a word char + whitespace
    // (i.e. follows a column name), NOT when the word IS a column name.
    '/(\w)\s+uuid\b/i' => '$1 varchar',
    '/(\w)\s+jsonb\b/i' => '$1 json',
    '/(\w)\s+bytea\b/i' => '$1 text',
    // Types the parser accepts but MySqlDataTypeToPhpTypeConverter doesn't
    // recognise (falls through to 'mixed', causing type errors):
    '/\bcharacter varying\b/i' => 'varchar',
    '/\btimestamp(\(\d+\))? without time zone\b/i' => 'timestamp',
    '/\btime(\(\d+\))? without time zone\b/i' => 'time',
];

$output = "-- Auto-generated by scripts/generate-larastan-schema.php\n";
$output .= "-- DO NOT EDIT — regenerate after re-squashing migrations.\n";
$output .= "-- Consumed by Larastan for model property discovery only.\n";
$output .= "-- NOT loaded at runtime — psql loads pgsql-schema.sql for that.\n\n";

foreach ($matches[1] as $createTable) {
    $mapped = preg_replace(array_keys($typeMap), array_values($typeMap), $createTable);

    // Ensure PostgreSQL nullable-by-default semantics are preserved.
    // The iamcal SQL parser defaults to NOT NULL when nullability is
    // unspecified (MySQL convention), but PostgreSQL defaults to nullable.
    // Without explicit NULL on nullable columns, Larastan reports false
    // positives (defensive null checks flagged as redundant on columns that
    // are genuinely nullable). We add explicit NULL to every column line
    // that doesn't already have a NULL/NOT NULL marker.
    $mapped = preg_replace_callback(
        // Column identifiers may contain digits (e.g. reminder_24h_sent_at,
        // geohash_4). Omitting 0-9 silently skipped those columns, leaving
        // them without a NULL marker so the parser defaulted them to NOT NULL
        // — the inverse of the bug this transform exists to fix.
        '/^(\s+[a-z0-9_]+\s+.+?)(\s*,?\s*)$/mi',
        static function (array $m): string {
            // Skip constraint definitions (CONSTRAINT, PRIMARY KEY, etc.)
            if (preg_match('/^(CONSTRAINT|PRIMARY|UNIQUE|FOREIGN|CHECK|KEY)\b/i', trim($m[1]))) {
                return $m[0];
            }
            // Skip if the column already has an explicit NULL/NOT NULL marker
            if (preg_match('/\bNULL\b/i', $m[1])) {
                return $m[0];
            }

            return $m[1].' NULL'.$m[2];
        },
        $mapped
    );

    $output .= $mapped."\n\n";
}

$bytes = file_put_contents($outputPath, $output);
$tableCount = count($matches[1]);

echo "Generated {$outputPath}\n";
echo "  Tables: {$tableCount}\n";
echo '  Size:   '.number_format($bytes)." bytes\n";
echo "  Type mappings: uuid→varchar, jsonb→json, bytea→text,\n";
echo "                 character varying→varchar, timestamp(0)→timestamp, time(0)→time\n";
echo "  Nullable: explicit NULL added (PostgreSQL defaults to nullable)\n";

// ── Self-test: verify the generated file parses correctly ────────────
// Re-parse the output through Larastan's SQL parser and assert that key
// columns are discovered. This catches silent corruption from regex edge
// cases before the file is committed.
require_once __DIR__.'/../vendor/autoload.php';

$parser = new IamcalSqlParser;
try {
    $tables = $parser->parseTables(file_get_contents($outputPath));
} catch (Throwable $e) {
    fwrite(STDERR, "\nSELF-TEST FAILED: generated file does not parse.\n");
    fwrite(STDERR, '  Error: '.$e->getMessage()."\n");
    exit(1);
}

// Build a lookup for spot-checks
$tableLookup = [];
foreach ($tables as $t) {
    $tableLookup[$t->name] = $t;
}

// Assertions on known tricky columns. Each row verifies column presence
// and, where 'nullable' is non-null, that the inferred nullability matches
// PostgreSQL reality. The nullability checks guard the [a-z0-9_]+ regex:
// digit-bearing column names must still receive the NULL marker.
$checks = [
    // [table, column, expectedNullable, reason]  (null = presence-only)
    ['media', 'uuid', null, 'column named uuid with type uuid (type-position regex edge case)'],
    ['short_links', 'linkable_type', null, 'morph column — must be discoverable for policies'],
    ['session_zero_surveys', 'uuid', null, 'column named uuid, must not be corrupted to varchar'],
    ['users', 'id', false, 'primary key — must be inferred NOT NULL'],
    ['games', 'share_token', true, 'nullable uuid — must be inferred nullable'],
    ['games', 'max_players', false, "DEFAULT '6' ... NOT NULL — must stay NOT NULL"],
    ['games', 'reminder_24h_sent_at', true, 'digit in name — must be inferred nullable'],
    ['locations', 'geohash_4', true, 'digit in name — must be inferred nullable'],
];

$errors = [];
foreach ($checks as [$table, $column, $expectedNullable, $reason]) {
    if (! isset($tableLookup[$table])) {
        $errors[] = "  MISSING TABLE: {$table} ({$reason})";

        continue;
    }

    $found = null;
    foreach ($tableLookup[$table]->columns as $c) {
        if ($c->name === $column) {
            $found = $c;

            break;
        }
    }

    if ($found === null) {
        $errors[] = "  MISSING COLUMN: {$table}.{$column} ({$reason})";

        continue;
    }

    if ($expectedNullable !== null && $found->nullable !== $expectedNullable) {
        $got = $found->nullable ? 'nullable' : 'NOT NULL';
        $want = $expectedNullable ? 'nullable' : 'NOT NULL';
        $errors[] = "  NULLABILITY MISMATCH: {$table}.{$column} inferred {$got}, expected {$want} ({$reason})";
    }
}

if (! empty($errors)) {
    fwrite(STDERR, "\nSELF-TEST FAILED: key columns not discovered.\n");
    foreach ($errors as $error) {
        fwrite(STDERR, $error."\n");
    }
    exit(1);
}

echo "\nSelf-test passed: ".count($tables).' tables, '.count($checks)." key columns verified.\n";
