#!/usr/bin/env php
<?php

/**
 * Generate a Larastan-compatible schema file from the PostgreSQL schema dump.
 *
 * Problem: Larastan's SQL parsers (iamcal, phpMyAdmin) cannot parse
 * PostgreSQL dump output. Two issues:
 *   1. psql meta-commands (\restrict, \connect, \.) break the tokeniser
 *   2. PostgreSQL-specific types (uuid, jsonb, bytea) are rejected by the
 *      iamcal parser, which is MySQL-focused
 *
 * Solution: extract only the CREATE TABLE statements from the runtime
 * dump and map the three problematic types to parser-friendly equivalents.
 * The type mapping is safe for static analysis — Larastan only needs to
 * know which COLUMNS exist and whether they're nullable; the exact storage
 * type is irrelevant for property-access checking.
 *
 * Usage:  php scripts/generate-larastan-schema.php
 * Run after re-squashing (schema:dump --prune) to regenerate.
 */
$dumpPath = __DIR__.'/../database/schema/pgsql-schema.sql';
$outputPath = __DIR__.'/../database/schema/larastan-schema.sql';

if (! file_exists($dumpPath)) {
    fwrite(STDERR, "Error: {$dumpPath} not found. Run schema:dump first.\n");
    exit(1);
}

$sql = file_get_contents($dumpPath);

// Extract only CREATE TABLE statements — the DDL Larastan needs.
// Everything else (COPY data, ALTER TABLE constraints, triggers, functions,
// sequences, psql meta-commands) is irrelevant for column discovery.
preg_match_all('/^(CREATE TABLE [^;]+;)\s*$/ms', $sql, $matches);

if (empty($matches[1])) {
    fwrite(STDERR, "Error: no CREATE TABLE statements found in {$dumpPath}\n");
    exit(1);
}

$typeMap = [
    // Types the iamcal SQL parser rejects entirely (causes a fatal parse error).
    // Match only in TYPE position: preceded by a word char + whitespace
    // (i.e. follows a column name), NOT when the word IS a column name.
    '/(\w)\s+uuid\b/i' => '$1 varchar',
    '/(\w)\s+jsonb\b/i' => '$1 json',
    '/(\w)\s+bytea\b/i' => '$1 text',
    // Types the parser accepts but MySqlDataTypeToPhpTypeConverter doesn't
    // recognise (falls through to 'mixed', causing type errors):
    '/\bcharacter varying\b/i' => 'varchar',
    '/\btimestamp(\(\d+\))? without time zone\b/i' => 'timestamp',
    '/\btime(\(\d+\))? without time zone\b/i' => 'time',
];

$output = "-- Auto-generated by scripts/generate-larastan-schema.php\n";
$output .= "-- DO NOT EDIT — regenerate after re-squashing migrations.\n";
$output .= "-- This file is consumed by Larastan for model property discovery.\n";
$output .= "-- It is NOT loaded at runtime (psql loads pgsql-schema.sql for that).\n";
$output .= "-- PostgreSQL-specific types are mapped to parser-friendly equivalents.\n\n";

foreach ($matches[1] as $createTable) {
    $mapped = preg_replace(array_keys($typeMap), array_values($typeMap), $createTable);

    // Blueprint's SchemaAggregator hardcodes created_at/updated_at as nullable
    // (timestamps() always creates nullable columns). Strip NOT NULL from these
    // columns so the SQL schema matches Blueprint's inference.
    $mapped = preg_replace('/^((?:\s*)(?:created_at|updated_at)\b.*?)\s+NOT NULL/m', '$1', $mapped);

    $output .= $mapped."\n\n";
}

$bytes = file_put_contents($outputPath, $output);
$tableCount = count($matches[1]);

echo "Generated {$outputPath}\n";
echo "  Tables: {$tableCount}\n";
echo '  Size:   '.number_format($bytes)." bytes\n";
echo "  Types mapped: uuid→varchar, jsonb→json, bytea→text, character varying→varchar, timestamp(0) without time zone→timestamp, time(0) without time zone→time\n";
