-- Auto-generated by scripts/generate-larastan-schema.php
-- DO NOT EDIT — regenerate after re-squashing migrations.
-- This file is consumed by Larastan for model property discovery.
-- It is NOT loaded at runtime (psql loads pgsql-schema.sql for that).
-- PostgreSQL-specific types are mapped to parser-friendly equivalents.

CREATE TABLE public.activity_logs (
    subject_type varchar(255),
    subject_id varchar(255),
    event_type varchar(255) NOT NULL,
    properties json,
    created_at timestamp,
    user_id varchar NOT NULL,
    id varchar NOT NULL
);

CREATE TABLE public.attendance_reports (
    id varchar NOT NULL,
    game_id varchar NOT NULL,
    status varchar(255) NOT NULL,
    weight_applied double precision DEFAULT '1'::double precision NOT NULL,
    is_corroborated boolean DEFAULT false NOT NULL,
    quarantined boolean DEFAULT false NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    reported_id varchar NOT NULL,
    reporter_id varchar NOT NULL,
    reason text,
    CONSTRAINT attendance_reports_status_check CHECK (((status)::text = ANY ((ARRAY['attended'::varchar, 'no_show'::varchar, 'late_cancel'::varchar, 'excused'::varchar, 'cancelled_early'::varchar])::text[])))
);

CREATE TABLE public.bgg_sync_logs (
    status varchar(255) NOT NULL,
    bgg_ids json,
    items_synced integer DEFAULT 0 NOT NULL,
    items_failed integer DEFAULT 0 NOT NULL,
    error_message text,
    started_at timestamp NOT NULL,
    completed_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    game_system_id varchar,
    id varchar NOT NULL
);

CREATE TABLE public.cache (
    key varchar(255) NOT NULL,
    value text NOT NULL,
    expiration bigint NOT NULL
);

CREATE TABLE public.cache_locks (
    key varchar(255) NOT NULL,
    owner varchar(255) NOT NULL,
    expiration bigint NOT NULL
);

CREATE TABLE public.campaign_applications (
    id varchar NOT NULL,
    campaign_id varchar NOT NULL,
    status varchar(255) DEFAULT 'pending'::varchar NOT NULL,
    message text,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL,
    CONSTRAINT campaign_applications_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::varchar, 'approved'::varchar, 'rejected'::varchar])::text[])))
);

CREATE TABLE public.campaign_game_system (
    campaign_id varchar NOT NULL,
    game_system_id varchar NOT NULL
);

CREATE TABLE public.campaign_participants (
    id varchar NOT NULL,
    campaign_id varchar NOT NULL,
    role varchar(255) DEFAULT 'player'::varchar NOT NULL,
    status varchar(255) DEFAULT 'pending'::varchar NOT NULL,
    benched_at timestamp,
    user_id varchar,
    join_source varchar,
    short_link_id bigint,
    removed_by varchar,
    removed_at timestamp,
    invitee_email varchar(255),
    waitlisted_at timestamp,
    confirmation_expires_at timestamp,
    confirmation_attempts integer,
    created_at timestamp,
    CONSTRAINT campaign_participants_join_source_check CHECK (((join_source)::text = ANY (ARRAY[('friend_invite'::varchar)::text, ('share_link'::varchar)::text, ('application'::varchar)::text, ('email_invite'::varchar)::text, ('short_link'::varchar)::text]))),
    CONSTRAINT campaign_participants_role_check CHECK (((role)::text = ANY ((ARRAY['owner'::varchar, 'player'::varchar, 'invited'::varchar, 'applicant'::varchar])::text[]))),
    CONSTRAINT campaign_participants_status_check CHECK (((status)::text = ANY (ARRAY[('approved'::varchar)::text, ('rejected'::varchar)::text, ('pending'::varchar)::text, ('waitlisted'::varchar)::text, ('benched'::varchar)::text, ('removed'::varchar)::text])))
);

CREATE TABLE public.campaigns (
    id varchar NOT NULL,
    name json NOT NULL,
    description json NOT NULL,
    recurrence varchar(255) NOT NULL,
    time_of_day varchar(255) NOT NULL,
    session_duration double precision NOT NULL,
    price_per_session double precision,
    language varchar(255) NOT NULL,
    status varchar(255) DEFAULT 'active'::varchar NOT NULL,
    minimum_requirements json,
    visibility varchar(255) DEFAULT 'public'::varchar NOT NULL,
    safety_rules json,
    created_at timestamp,
    updated_at timestamp,
    min_players smallint,
    max_players smallint,
    experience_level varchar(30),
    complexity numeric(3,2),
    vibe_flags json,
    location_id varchar,
    owner_id varchar NOT NULL,
    share_token varchar,
    share_token_expires_at timestamp,
    location_instructions text,
    bench_mode boolean DEFAULT false NOT NULL,
    game_type varchar(20),
    host_note text,
    CONSTRAINT campaigns_recurrence_check CHECK (((recurrence)::text = ANY ((ARRAY['weekly'::varchar, 'bi-weekly'::varchar, 'monthly'::varchar])::text[]))),
    CONSTRAINT campaigns_status_check CHECK (((status)::text = ANY ((ARRAY['active'::varchar, 'cancelled'::varchar, 'completed'::varchar])::text[]))),
    CONSTRAINT campaigns_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['public'::varchar, 'protected'::varchar, 'private'::varchar])::text[])))
);

CREATE TABLE public.customers (
    id bigint NOT NULL,
    billable_type varchar(255) NOT NULL,
    paddle_id varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    trial_ends_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    billable_id varchar(36)
);

CREATE TABLE public.escalated_agent_capacity (
    id bigint NOT NULL,
    channel varchar(255) DEFAULT 'default'::varchar NOT NULL,
    max_concurrent integer DEFAULT 10 NOT NULL,
    current_count integer DEFAULT 0 NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar
);

CREATE TABLE public.escalated_agent_profiles (
    id bigint NOT NULL,
    agent_type varchar(255) DEFAULT 'full'::varchar NOT NULL,
    max_tickets integer,
    created_at timestamp,
    updated_at timestamp,
    chat_status varchar(255) DEFAULT 'offline'::varchar NOT NULL,
    user_id varchar
);

CREATE TABLE public.escalated_agent_skill (
    id bigint NOT NULL,
    skill_id bigint NOT NULL,
    proficiency integer DEFAULT 1 NOT NULL,
    user_id varchar
);

CREATE TABLE public.escalated_api_tokens (
    id bigint NOT NULL,
    tokenable_type varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    token varchar(64) NOT NULL,
    abilities json,
    last_used_at timestamp,
    last_used_ip varchar(45),
    expires_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    tokenable_id varchar
);

CREATE TABLE public.escalated_article_categories (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    parent_id bigint,
    "position" integer DEFAULT 0 NOT NULL,
    description text,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_articles (
    id bigint NOT NULL,
    category_id bigint,
    title varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    body text,
    status varchar(255) DEFAULT 'draft'::varchar NOT NULL,
    view_count integer DEFAULT 0 NOT NULL,
    helpful_count integer DEFAULT 0 NOT NULL,
    not_helpful_count integer DEFAULT 0 NOT NULL,
    published_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    author_id varchar
);

CREATE TABLE public.escalated_attachments (
    id bigint NOT NULL,
    attachable_type varchar(255) NOT NULL,
    filename varchar(255) NOT NULL,
    original_filename varchar(255) NOT NULL,
    mime_type varchar(255) NOT NULL,
    size bigint NOT NULL,
    disk varchar(255) NOT NULL,
    path varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    attachable_id varchar
);

CREATE TABLE public.escalated_audit_logs (
    id bigint NOT NULL,
    action varchar(255) NOT NULL,
    auditable_type varchar(255) NOT NULL,
    auditable_id bigint NOT NULL,
    old_values json,
    new_values json,
    ip_address varchar(255),
    user_agent varchar(255),
    created_at timestamp,
    user_id varchar
);

CREATE TABLE public.escalated_automations (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    conditions json NOT NULL,
    actions json NOT NULL,
    active boolean DEFAULT true NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    last_run_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_business_schedules (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    timezone varchar(255) DEFAULT 'UTC'::varchar NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    schedule json NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_canned_responses (
    id bigint NOT NULL,
    title varchar(255) NOT NULL,
    body text NOT NULL,
    category varchar(255),
    is_shared boolean DEFAULT true NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    created_by varchar
);

CREATE TABLE public.escalated_chat_routing_rules (
    id bigint NOT NULL,
    department_id bigint,
    routing_strategy varchar(255) DEFAULT 'round_robin'::varchar NOT NULL,
    offline_behavior varchar(255) DEFAULT 'ticket_fallback'::varchar NOT NULL,
    max_queue_size integer DEFAULT 10 NOT NULL,
    max_concurrent_per_agent integer DEFAULT 5 NOT NULL,
    auto_close_after_minutes integer DEFAULT 30 NOT NULL,
    queue_message text,
    offline_message text,
    is_active boolean DEFAULT true NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_chat_sessions (
    id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    customer_session_id varchar(64) NOT NULL,
    status varchar(255) DEFAULT 'waiting'::varchar NOT NULL,
    started_at timestamp NOT NULL,
    ended_at timestamp,
    customer_typing_at timestamp,
    agent_typing_at timestamp,
    metadata json,
    rating smallint,
    rating_comment text,
    created_at timestamp,
    updated_at timestamp,
    agent_id varchar
);

CREATE TABLE public.escalated_contacts (
    id bigint NOT NULL,
    email varchar(320) NOT NULL,
    name varchar(255),
    metadata json,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar
);

CREATE TABLE public.escalated_custom_field_values (
    id bigint NOT NULL,
    custom_field_id bigint NOT NULL,
    entity_type varchar(255) NOT NULL,
    value text,
    created_at timestamp,
    updated_at timestamp,
    entity_id varchar
);

CREATE TABLE public.escalated_custom_fields (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    context varchar(255) DEFAULT 'ticket'::varchar NOT NULL,
    options json,
    required boolean DEFAULT false NOT NULL,
    placeholder varchar(255),
    description text,
    validation_rules json,
    "position" integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    conditions json
);

CREATE TABLE public.escalated_custom_object_records (
    id bigint NOT NULL,
    object_id bigint NOT NULL,
    data json NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_custom_objects (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    fields_schema json NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_delayed_actions (
    id bigint NOT NULL,
    workflow_id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    action json NOT NULL,
    remaining_actions json NOT NULL,
    execute_at timestamp NOT NULL,
    executed boolean DEFAULT false NOT NULL,
    cancelled boolean DEFAULT false NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_department_agent (
    department_id bigint NOT NULL,
    agent_id varchar
);

CREATE TABLE public.escalated_departments (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    description text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_escalation_rules (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    description text,
    trigger_type varchar(255) NOT NULL,
    conditions json NOT NULL,
    actions json NOT NULL,
    "order" integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    category varchar(255) DEFAULT 'Uncategorized'::varchar NOT NULL
);

CREATE TABLE public.escalated_holidays (
    id bigint NOT NULL,
    schedule_id bigint NOT NULL,
    name varchar(255) NOT NULL,
    date date NOT NULL,
    recurring boolean DEFAULT false NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_import_jobs (
    id varchar NOT NULL,
    platform varchar(50) NOT NULL,
    status varchar(30) DEFAULT 'pending'::varchar NOT NULL,
    credentials text,
    field_mappings json,
    progress json,
    error_log json,
    started_at timestamp,
    completed_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar
);

CREATE TABLE public.escalated_import_source_maps (
    id bigint NOT NULL,
    import_job_id varchar NOT NULL,
    entity_type varchar(50) NOT NULL,
    source_id varchar(255) NOT NULL,
    escalated_id varchar(255) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.escalated_inbound_emails (
    id bigint NOT NULL,
    message_id varchar(255),
    from_email varchar(255) NOT NULL,
    from_name varchar(255),
    to_email varchar(255) NOT NULL,
    subject varchar(255) NOT NULL,
    body_text text,
    body_html text,
    raw_headers text,
    ticket_id bigint,
    reply_id bigint,
    status varchar(255) DEFAULT 'pending'::varchar NOT NULL,
    adapter varchar(255) NOT NULL,
    error_message text,
    processed_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_macros (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    description varchar(255),
    actions json NOT NULL,
    is_shared boolean DEFAULT true NOT NULL,
    "order" integer DEFAULT 0 NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    created_by varchar
);

CREATE TABLE public.escalated_mentions (
    id bigint NOT NULL,
    reply_id bigint NOT NULL,
    read_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar
);

CREATE TABLE public.escalated_permissions (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    "group" varchar(255) NOT NULL,
    description text
);

CREATE TABLE public.escalated_plugin_store (
    id bigint NOT NULL,
    plugin varchar(50) NOT NULL,
    collection varchar(50) NOT NULL,
    key varchar(255),
    data json,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_plugins (
    id bigint NOT NULL,
    slug varchar(255) NOT NULL,
    is_active boolean DEFAULT false NOT NULL,
    activated_at timestamp,
    deactivated_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_replies (
    id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    author_type varchar(255),
    body text NOT NULL,
    is_internal_note boolean DEFAULT false NOT NULL,
    type varchar(255) DEFAULT 'reply'::varchar NOT NULL,
    metadata json,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp,
    is_pinned boolean DEFAULT false NOT NULL,
    author_id varchar
);

CREATE TABLE public.escalated_role_permission (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);

CREATE TABLE public.escalated_role_user (
    role_id bigint NOT NULL,
    user_id varchar
);

CREATE TABLE public.escalated_roles (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    description text,
    is_system boolean DEFAULT false NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_satisfaction_ratings (
    id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    rating smallint NOT NULL,
    comment text,
    rated_by_type varchar(255),
    created_at timestamp,
    rated_by_id varchar
);

CREATE TABLE public.escalated_saved_views (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    filters json NOT NULL,
    is_shared boolean DEFAULT false NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    icon varchar(255),
    color varchar(255),
    created_at timestamp,
    updated_at timestamp,
    user_id varchar
);

CREATE TABLE public.escalated_settings (
    id bigint NOT NULL,
    key varchar(255) NOT NULL,
    value text,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_side_conversation_replies (
    id bigint NOT NULL,
    side_conversation_id bigint NOT NULL,
    body text NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    author_id varchar
);

CREATE TABLE public.escalated_side_conversations (
    id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    subject varchar(255) NOT NULL,
    channel varchar(255) DEFAULT 'internal'::varchar NOT NULL,
    status varchar(255) DEFAULT 'open'::varchar NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    created_by varchar
);

CREATE TABLE public.escalated_skills (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_sla_policies (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    description text,
    is_default boolean DEFAULT false NOT NULL,
    first_response_hours json NOT NULL,
    resolution_hours json NOT NULL,
    business_hours_only boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_tags (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    color varchar(255) DEFAULT '#6B7280'::varchar NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_ticket_activities (
    id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    causer_type varchar(255),
    type varchar(255) NOT NULL,
    properties json,
    created_at timestamp,
    updated_at timestamp,
    causer_id varchar
);

CREATE TABLE public.escalated_ticket_followers (
    ticket_id bigint NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar
);

CREATE TABLE public.escalated_ticket_links (
    id bigint NOT NULL,
    parent_ticket_id bigint NOT NULL,
    child_ticket_id bigint NOT NULL,
    link_type varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_ticket_statuses (
    id bigint NOT NULL,
    label varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    color varchar(255) DEFAULT '#6b7280'::varchar NOT NULL,
    description text,
    "position" integer DEFAULT 0 NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_ticket_subjects (
    id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    subject_type varchar(255) NOT NULL,
    subject_id varchar(255) NOT NULL,
    role varchar(255),
    "position" integer DEFAULT 0 NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_ticket_tag (
    ticket_id bigint NOT NULL,
    tag_id bigint NOT NULL
);

CREATE TABLE public.escalated_tickets (
    id bigint NOT NULL,
    reference varchar(255) NOT NULL,
    requester_type varchar(255),
    subject varchar(255) NOT NULL,
    description text NOT NULL,
    status varchar(255) DEFAULT 'open'::varchar NOT NULL,
    priority varchar(255) DEFAULT 'medium'::varchar NOT NULL,
    channel varchar(255) DEFAULT 'web'::varchar NOT NULL,
    department_id bigint,
    sla_policy_id bigint,
    first_response_at timestamp,
    first_response_due_at timestamp,
    resolution_due_at timestamp,
    sla_first_response_breached boolean DEFAULT false NOT NULL,
    sla_resolution_breached boolean DEFAULT false NOT NULL,
    resolved_at timestamp,
    closed_at timestamp,
    metadata json,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp,
    guest_name varchar(255),
    guest_email varchar(255),
    guest_token varchar(64),
    merged_into_id bigint,
    type varchar(255) DEFAULT 'question'::varchar NOT NULL,
    ticket_type varchar(255) DEFAULT 'question'::varchar NOT NULL,
    snoozed_until timestamp,
    status_before_snooze varchar(255),
    chat_ended_at timestamp,
    chat_metadata json,
    contact_id bigint,
    requester_id varchar,
    assigned_to varchar,
    snoozed_by varchar
);

CREATE TABLE public.escalated_two_factor (
    id bigint NOT NULL,
    secret text NOT NULL,
    recovery_codes text,
    confirmed_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar
);

CREATE TABLE public.escalated_webhook_deliveries (
    id bigint NOT NULL,
    webhook_id bigint NOT NULL,
    event varchar(255) NOT NULL,
    payload json,
    response_code smallint,
    response_body text,
    attempts smallint DEFAULT '0'::smallint NOT NULL,
    delivered_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_webhooks (
    id bigint NOT NULL,
    url varchar(255) NOT NULL,
    events json NOT NULL,
    secret varchar(255),
    active boolean DEFAULT true NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_workflow_logs (
    id bigint NOT NULL,
    workflow_id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    trigger_event varchar(255) NOT NULL,
    conditions_matched boolean NOT NULL,
    actions_executed json,
    error text,
    started_at timestamp,
    completed_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.escalated_workflows (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    description text,
    trigger_event varchar(255) NOT NULL,
    conditions json NOT NULL,
    actions json NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    last_triggered_at timestamp,
    trigger_count integer DEFAULT 0 NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    created_by varchar
);

CREATE TABLE public.event_announcements (
    id varchar NOT NULL,
    event_id varchar NOT NULL,
    title json NOT NULL,
    content json NOT NULL,
    is_pinned boolean DEFAULT false NOT NULL,
    is_published boolean DEFAULT false NOT NULL,
    visibility varchar(50) DEFAULT 'all'::varchar NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    author_id varchar NOT NULL
);

CREATE TABLE public.event_registrations (
    id varchar NOT NULL,
    event_id varchar NOT NULL,
    registration_type varchar(255) NOT NULL,
    division varchar(100),
    status varchar(50) DEFAULT 'pending'::varchar NOT NULL,
    payment_status varchar(50) DEFAULT 'pending'::varchar NOT NULL,
    payment_id varchar(255),
    roster json,
    notes text,
    internal_notes text,
    confirmed_at timestamp,
    cancelled_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    team_id varchar,
    user_id varchar NOT NULL,
    CONSTRAINT event_registrations_registration_type_check CHECK (((registration_type)::text = ANY ((ARRAY['team'::varchar, 'individual'::varchar])::text[])))
);

CREATE TABLE public.events (
    id varchar NOT NULL,
    name json NOT NULL,
    slug varchar(255) NOT NULL,
    description json,
    short_description json,
    type varchar(255) DEFAULT 'tournament'::varchar NOT NULL,
    status varchar(255) DEFAULT 'draft'::varchar NOT NULL,
    venue_name varchar(255),
    venue_address text,
    city varchar(255),
    country varchar(3),
    postal_code varchar(255),
    start_date date NOT NULL,
    end_date date NOT NULL,
    registration_opens_at timestamp,
    registration_closes_at timestamp,
    registration_type varchar(255) DEFAULT 'team'::varchar NOT NULL,
    max_teams integer,
    max_participants integer,
    min_players_per_team integer DEFAULT 7 NOT NULL,
    max_players_per_team integer DEFAULT 21 NOT NULL,
    team_registration_fee integer DEFAULT 0 NOT NULL,
    individual_registration_fee integer DEFAULT 0 NOT NULL,
    early_bird_discount integer,
    early_bird_deadline timestamp,
    contact_email varchar(255),
    contact_phone varchar(255),
    rules json,
    schedule json,
    divisions json,
    amenities json,
    requirements json,
    logo_url varchar(255),
    banner_url varchar(255),
    is_public boolean DEFAULT true NOT NULL,
    is_featured boolean DEFAULT false NOT NULL,
    metadata json,
    created_at timestamp,
    updated_at timestamp,
    language varchar(7),
    location_id varchar,
    organizer_id varchar NOT NULL,
    CONSTRAINT events_registration_type_check CHECK (((registration_type)::text = ANY ((ARRAY['team'::varchar, 'individual'::varchar, 'both'::varchar])::text[]))),
    CONSTRAINT events_status_check CHECK (((status)::text = ANY ((ARRAY['draft'::varchar, 'published'::varchar, 'registration_open'::varchar, 'registration_closed'::varchar, 'in_progress'::varchar, 'completed'::varchar, 'cancelled'::varchar])::text[]))),
    CONSTRAINT events_type_check CHECK (((type)::text = ANY ((ARRAY['tournament'::varchar, 'league'::varchar, 'camp'::varchar, 'clinic'::varchar, 'social'::varchar, 'other'::varchar])::text[])))
);

CREATE TABLE public.failed_jobs (
    id bigint NOT NULL,
    uuid varchar(255) NOT NULL,
    connection text NOT NULL,
    queue text NOT NULL,
    payload text NOT NULL,
    exception text NOT NULL,
    failed_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE public.game_applications (
    id varchar NOT NULL,
    game_id varchar NOT NULL,
    status varchar(255) DEFAULT 'pending'::varchar NOT NULL,
    message text,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL,
    CONSTRAINT game_applications_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::varchar, 'approved'::varchar, 'rejected'::varchar])::text[])))
);

CREATE TABLE public.game_bulletins (
    id varchar NOT NULL,
    game_id varchar NOT NULL,
    user_id varchar NOT NULL,
    content varchar(280) NOT NULL,
    expires_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.game_game_system (
    game_id varchar NOT NULL,
    game_system_id varchar NOT NULL
);

CREATE TABLE public.game_participants (
    id varchar NOT NULL,
    game_id varchar NOT NULL,
    role varchar(255) DEFAULT 'player'::varchar NOT NULL,
    status varchar(255) DEFAULT 'pending'::varchar NOT NULL,
    attendance_status varchar(255),
    confirmation_expires_at timestamp,
    waitlisted_at timestamp,
    attendance_reported_at timestamp,
    attendance_weight double precision,
    benched_at timestamp,
    created_at timestamp,
    confirmation_attempts integer,
    user_id varchar,
    attendance_reported_by varchar,
    join_source varchar,
    short_link_id bigint,
    removed_by varchar,
    removed_at timestamp,
    invitee_email varchar(255),
    attendance_disputed_at timestamp,
    approved_at timestamp,
    promoted_manually boolean DEFAULT false NOT NULL,
    CONSTRAINT game_participants_attendance_status_check CHECK (((attendance_status)::text = ANY ((ARRAY['attended'::varchar, 'no_show'::varchar, 'late_cancel'::varchar, 'excused'::varchar, 'cancelled_early'::varchar])::text[]))),
    CONSTRAINT game_participants_join_source_check CHECK (((join_source)::text = ANY (ARRAY[('friend_invite'::varchar)::text, ('share_link'::varchar)::text, ('application'::varchar)::text, ('email_invite'::varchar)::text, ('short_link'::varchar)::text]))),
    CONSTRAINT game_participants_role_check CHECK (((role)::text = ANY ((ARRAY['owner'::varchar, 'player'::varchar, 'invited'::varchar, 'applicant'::varchar])::text[]))),
    CONSTRAINT game_participants_status_check CHECK (((status)::text = ANY (ARRAY[('approved'::varchar)::text, ('rejected'::varchar)::text, ('pending'::varchar)::text, ('waitlisted'::varchar)::text, ('benched'::varchar)::text, ('removed'::varchar)::text])))
);

CREATE TABLE public.game_system_categories (
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    description text,
    id varchar NOT NULL
);

CREATE TABLE public.game_system_category (
    game_system_id varchar NOT NULL,
    game_system_category_id varchar NOT NULL
);

CREATE TABLE public.game_system_category_relations (
    type varchar(255) DEFAULT 'similar'::varchar,
    category_id varchar NOT NULL,
    related_category_id varchar NOT NULL
);

CREATE TABLE public.game_system_designer (
    game_system_id varchar NOT NULL,
    game_system_designer_id varchar NOT NULL
);

CREATE TABLE public.game_system_designers (
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    id varchar NOT NULL
);

CREATE TABLE public.game_system_families (
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    id varchar NOT NULL
);

CREATE TABLE public.game_system_family (
    game_system_id varchar NOT NULL,
    game_system_family_id varchar NOT NULL
);

CREATE TABLE public.game_system_mechanic (
    game_system_id varchar NOT NULL,
    game_system_mechanic_id varchar NOT NULL
);

CREATE TABLE public.game_system_mechanic_relations (
    type varchar(255) DEFAULT 'similar'::varchar,
    mechanic_id varchar NOT NULL,
    related_mechanic_id varchar NOT NULL
);

CREATE TABLE public.game_system_mechanics (
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    description text,
    id varchar NOT NULL
);

CREATE TABLE public.game_system_publisher (
    game_system_id varchar NOT NULL,
    game_system_publisher_id varchar NOT NULL
);

CREATE TABLE public.game_system_publishers (
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    id varchar NOT NULL
);

CREATE TABLE public.game_systems (
    name json NOT NULL,
    slug varchar(255) NOT NULL,
    description json,
    images json,
    min_players integer,
    max_players integer,
    optimal_players integer,
    average_play_time integer,
    age_rating varchar(50),
    complexity_rating varchar(50),
    year_released integer,
    created_at timestamp,
    updated_at timestamp,
    bgg_id integer,
    bgg_type varchar(255),
    thumbnail_url varchar(255),
    bgg_average_rating numeric(4,2),
    bgg_bayes_average numeric(4,2),
    bgg_rank integer,
    bgg_users_rated integer,
    bgg_average_weight numeric(4,2),
    bgg_last_synced_at timestamp,
    type varchar(255) DEFAULT 'boardgame'::varchar NOT NULL,
    source varchar(255),
    source_slug varchar(255),
    creator varchar(255),
    player_range varchar(255),
    sp_rating numeric(3,2),
    sp_review_count integer,
    faq_content text,
    external_links text,
    showcases text,
    instructions text,
    platform_score integer DEFAULT 0 NOT NULL,
    id varchar NOT NULL,
    base_game_id varchar
);

CREATE TABLE public.games (
    id varchar NOT NULL,
    campaign_id varchar,
    name json NOT NULL,
    date_time timestamp NOT NULL,
    description json NOT NULL,
    expected_duration double precision NOT NULL,
    price double precision,
    language varchar(50) NOT NULL,
    location json NOT NULL,
    status varchar(255) DEFAULT 'scheduled'::varchar NOT NULL,
    minimum_requirements json,
    visibility varchar(255) DEFAULT 'public'::varchar NOT NULL,
    safety_rules json,
    created_at timestamp,
    updated_at timestamp,
    min_players smallint DEFAULT '2'::smallint NOT NULL,
    max_players smallint DEFAULT '6'::smallint NOT NULL,
    experience_level varchar(30),
    complexity numeric(3,2),
    vibe_flags json,
    game_type varchar(255) DEFAULT 'board_game'::varchar NOT NULL,
    reminder_sent_at timestamp,
    recap text,
    min_reliability_preference numeric(5,2),
    reminder_24h_sent_at timestamp,
    location_id varchar,
    owner_id varchar NOT NULL,
    share_token varchar,
    share_token_expires_at timestamp,
    location_instructions text,
    bench_mode boolean DEFAULT false NOT NULL,
    attendance_window_opens_at timestamp,
    attendance_window_closes_at timestamp,
    attendance_resolved_at timestamp,
    attendance_resolution_method varchar(255),
    host_note text,
    CONSTRAINT games_attendance_resolution_method_check CHECK (((attendance_resolution_method)::text = ANY ((ARRAY['early_consensus'::varchar, 'timeout'::varchar, 'manual'::varchar])::text[]))),
    CONSTRAINT games_status_check CHECK (((status)::text = ANY ((ARRAY['scheduled'::varchar, 'canceled'::varchar, 'completed'::varchar])::text[]))),
    CONSTRAINT games_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['public'::varchar, 'protected'::varchar, 'private'::varchar])::text[])))
);

CREATE TABLE public.gm_profiles (
    id varchar NOT NULL,
    bio text,
    specializations json,
    slug varchar(255) NOT NULL,
    average_rating numeric(3,2),
    review_count integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL
);

CREATE TABLE public.gm_social_links (
    id bigint NOT NULL,
    user_id varchar NOT NULL,
    platform varchar(50) NOT NULL,
    handle varchar(255) NOT NULL,
    instance varchar(255),
    url varchar(500),
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.job_batches (
    id varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    total_jobs integer NOT NULL,
    pending_jobs integer NOT NULL,
    failed_jobs integer NOT NULL,
    failed_job_ids text NOT NULL,
    options text,
    cancelled_at integer,
    created_at integer,
    finished_at integer
);

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    queue varchar(255) NOT NULL,
    payload text NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer
);

CREATE TABLE public.linked_accounts (
    provider varchar(255) NOT NULL,
    provider_user_id varchar(255) NOT NULL,
    token text,
    refresh_token text,
    token_expires_at timestamp,
    provider_meta json,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL,
    id varchar NOT NULL
);

CREATE TABLE public.local_subscriptions (
    status varchar(255) DEFAULT 'active'::varchar NOT NULL,
    starts_at timestamp,
    ends_at timestamp,
    canceled_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL,
    id varchar NOT NULL,
    membership_type_id varchar NOT NULL
);

CREATE TABLE public.locations (
    name varchar(255),
    description text,
    address varchar(255),
    city varchar(255),
    postal_code varchar(20),
    country varchar(3),
    latitude numeric(10,7),
    longitude numeric(10,7),
    place_id varchar(255),
    source varchar(50),
    metadata json,
    created_at timestamp,
    updated_at timestamp,
    geohash_4 varchar(4),
    id varchar NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    venue_type varchar(50),
    venue_notes text,
    website_url varchar(500),
    managed_by varchar,
    venue_metadata json,
    slug varchar(255),
    drift_status varchar(20) DEFAULT 'clean'::varchar NOT NULL,
    drift_detected_at timestamp,
    drift_metadata json,
    average_rating numeric(3,2),
    review_count integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.media (
    model_type varchar(255) NOT NULL,
    model_id varchar(36) NOT NULL,
    uuid varchar,
    collection_name varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    file_name varchar(255) NOT NULL,
    mime_type varchar(255),
    disk varchar(255) NOT NULL,
    conversions_disk varchar(255),
    size bigint NOT NULL,
    manipulations json NOT NULL,
    custom_properties json NOT NULL,
    generated_conversions json NOT NULL,
    responsive_images json NOT NULL,
    order_column integer,
    created_at timestamp,
    updated_at timestamp,
    id varchar NOT NULL
);

CREATE TABLE public.membership_types (
    name varchar(255) NOT NULL,
    description varchar(1000),
    price_cents integer NOT NULL,
    duration_months integer NOT NULL,
    status varchar(50) DEFAULT 'active'::varchar NOT NULL,
    paddle_price_id varchar(255),
    metadata json,
    created_at timestamp,
    updated_at timestamp,
    type varchar(255) DEFAULT 'paddle'::varchar NOT NULL,
    id varchar NOT NULL
);

CREATE TABLE public.migrations (
    id integer NOT NULL,
    migration varchar(255) NOT NULL,
    batch integer NOT NULL
);

CREATE TABLE public.model_has_permissions (
    permission_id bigint NOT NULL,
    model_type varchar(255) NOT NULL,
    team_id varchar(36),
    model_id varchar(36)
);

CREATE TABLE public.model_has_roles (
    role_id bigint NOT NULL,
    model_type varchar(255) NOT NULL,
    team_id varchar(36),
    model_id varchar(36)
);

CREATE TABLE public.nearby_discovery_views (
    last_discovery_view timestamp,
    geohash_4 varchar(4),
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL,
    id varchar NOT NULL
);

CREATE TABLE public.notifications (
    id varchar NOT NULL,
    type varchar(255) NOT NULL,
    notifiable_type varchar(255) NOT NULL,
    data json NOT NULL,
    read_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    notifiable_id varchar(36)
);

CREATE TABLE public.password_reset_tokens (
    email varchar(255) NOT NULL,
    token varchar(255) NOT NULL,
    created_at timestamp
);

CREATE TABLE public.permissions (
    id bigint NOT NULL,
    name varchar(255) NOT NULL,
    guard_name varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.personal_access_tokens (
    id bigint NOT NULL,
    tokenable_type varchar(255) NOT NULL,
    tokenable_id bigint NOT NULL,
    name text NOT NULL,
    token varchar(64) NOT NULL,
    abilities text,
    last_used_at timestamp,
    expires_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.push_subscriptions (
    endpoint varchar(255) NOT NULL,
    p256h_key varchar(255) NOT NULL,
    auth_token varchar(255) NOT NULL,
    user_agent varchar(255),
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL,
    id varchar NOT NULL
);

CREATE TABLE public.reviews (
    id varchar NOT NULL,
    reviewable_type varchar(255) NOT NULL,
    reviewable_id varchar(36) NOT NULL,
    gm_profile_id varchar,
    rating smallint NOT NULL,
    body text,
    proficiency_tags json,
    status varchar(255) DEFAULT 'published'::varchar NOT NULL,
    reported_at timestamp,
    reply text,
    replied_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    report_reason varchar(255),
    reviewer_id varchar NOT NULL,
    reported_by varchar,
    CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)))
);

CREATE TABLE public.role_has_permissions (
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL
);

CREATE TABLE public.roles (
    id bigint NOT NULL,
    team_id varchar(36),
    name varchar(255) NOT NULL,
    guard_name varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.seo (
    id bigint NOT NULL,
    model_type varchar(255) NOT NULL,
    model_id varchar(36),
    description text,
    title varchar(255),
    image varchar(255),
    author varchar(255),
    robots varchar(255),
    canonical_url varchar(255),
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.session_debriefings (
    id varchar NOT NULL,
    game_id varchar NOT NULL,
    tool_type varchar(255) NOT NULL,
    responses json,
    submitted_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL,
    CONSTRAINT session_debriefings_tool_type_check CHECK (((tool_type)::text = ANY ((ARRAY['debriefing'::varchar, 'stars-and-wishes'::varchar])::text[])))
);

CREATE TABLE public.session_zero_confirmations (
    id varchar NOT NULL,
    session_zero_survey_id varchar NOT NULL,
    confirmed_at timestamp,
    user_id varchar
);

CREATE TABLE public.session_zero_surveys (
    id varchar NOT NULL,
    gm_profile_id varchar NOT NULL,
    game_id varchar,
    title varchar(255) NOT NULL,
    content json,
    uuid varchar(255) NOT NULL,
    status varchar(255) DEFAULT 'active'::varchar NOT NULL,
    confirmation_count integer DEFAULT 0 NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.sessions (
    id varchar(255) NOT NULL,
    ip_address varchar(45),
    user_agent text,
    payload text NOT NULL,
    last_activity integer NOT NULL,
    user_id varchar
);

CREATE TABLE public.short_link_hits (
    id bigint NOT NULL,
    short_link_id bigint NOT NULL,
    ip_address varchar(128),
    referer text,
    user_agent text,
    country_code varchar(2),
    hit_at timestamp NOT NULL,
    referer_domain varchar(255)
);

CREATE TABLE public.short_links (
    id bigint NOT NULL,
    code varchar(36) NOT NULL,
    url text NOT NULL,
    linkable_type varchar(255) NOT NULL,
    linkable_id varchar(255) NOT NULL,
    user_id varchar,
    label varchar(100),
    purpose varchar(50),
    expires_at timestamp,
    max_hits integer,
    hit_count integer DEFAULT 0 NOT NULL,
    last_hit_at timestamp,
    deleted_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.subscription_items (
    id bigint NOT NULL,
    subscription_id bigint NOT NULL,
    product_id varchar(255) NOT NULL,
    price_id varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp,
    updated_at timestamp
);

CREATE TABLE public.subscriptions (
    id bigint NOT NULL,
    billable_type varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    paddle_id varchar(255) NOT NULL,
    status varchar(255) NOT NULL,
    trial_ends_at timestamp,
    paused_at timestamp,
    ends_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    billable_id varchar(36)
);

CREATE TABLE public.suppressed_invite_emails (
    id bigint NOT NULL,
    email_hash varchar(64) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.team_members (
    role varchar(255) DEFAULT 'player'::varchar NOT NULL,
    status varchar(255) DEFAULT 'pending'::varchar NOT NULL,
    jersey_number varchar(3),
    "position" varchar(50),
    joined_at timestamp NOT NULL,
    left_at timestamp,
    notes text,
    team_id varchar NOT NULL,
    user_id varchar NOT NULL,
    invited_by varchar,
    id varchar NOT NULL,
    CONSTRAINT team_members_role_check CHECK (((role)::text = ANY ((ARRAY['captain'::varchar, 'coach'::varchar, 'player'::varchar, 'substitute'::varchar])::text[]))),
    CONSTRAINT team_members_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::varchar, 'active'::varchar, 'inactive'::varchar, 'removed'::varchar])::text[])))
);

CREATE TABLE public.teams (
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    description json,
    city varchar(255),
    country varchar(3),
    logo_url varchar(255),
    primary_color varchar(7),
    secondary_color varchar(7),
    founded_year varchar(4),
    website varchar(255),
    social_links json,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    id varchar NOT NULL,
    created_by varchar NOT NULL,
    language varchar(5)
);

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    billable_type varchar(255) NOT NULL,
    paddle_id varchar(255) NOT NULL,
    paddle_subscription_id varchar(255),
    invoice_number varchar(255),
    status varchar(255) NOT NULL,
    total varchar(255) NOT NULL,
    tax varchar(255) NOT NULL,
    currency varchar(3) NOT NULL,
    billed_at timestamp NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    billable_id varchar(36)
);

CREATE TABLE public.user_app_visits (
    visit_date date NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL,
    id varchar NOT NULL
);

CREATE TABLE public.user_game_system_preferences (
    preference_type varchar(255) NOT NULL,
    game_system_id varchar NOT NULL,
    user_id varchar NOT NULL,
    CONSTRAINT user_game_system_preferences_preference_type_check CHECK (((preference_type)::text = ANY ((ARRAY['favorite'::varchar, 'avoid'::varchar])::text[])))
);

CREATE TABLE public.user_relationships (
    type varchar(255) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    user_id varchar NOT NULL,
    related_user_id varchar NOT NULL,
    id varchar NOT NULL,
    CONSTRAINT user_relationships_type_check CHECK (((type)::text = ANY ((ARRAY['follow'::varchar, 'block'::varchar])::text[])))
);

CREATE TABLE public.user_vibe_preferences (
    vibe_preference_value varchar(255) NOT NULL,
    preference_type varchar(255) NOT NULL,
    user_id varchar NOT NULL,
    CONSTRAINT user_vibe_preferences_preference_type_check CHECK (((preference_type)::text = ANY ((ARRAY['favorite'::varchar, 'avoid'::varchar])::text[])))
);

CREATE TABLE public.users (
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    email_verified_at timestamp,
    password varchar(255),
    avatar_url varchar(255),
    profile_complete boolean DEFAULT false NOT NULL,
    gender varchar(255),
    pronouns varchar(255),
    phone varchar(255),
    privacy_settings json,
    profile_version integer DEFAULT 1 NOT NULL,
    profile_updated_at timestamp,
    remember_token varchar(100),
    created_at timestamp,
    updated_at timestamp,
    paddle_id varchar(255),
    trial_ends_at timestamp,
    password_set_at timestamp,
    is_disabled boolean DEFAULT false NOT NULL,
    disabled_at timestamp,
    can_create_public_entries boolean DEFAULT false NOT NULL,
    preferred_language varchar(10),
    location json,
    notification_settings json,
    reliability_score json,
    reliability_computed_at timestamp,
    location_id varchar,
    id varchar NOT NULL,
    bio text,
    slug varchar(255),
    max_links_per_entity integer DEFAULT 10 NOT NULL,
    anonymized_at timestamp,
    gender_consent boolean DEFAULT false NOT NULL,
    privacy_policy_accepted_at timestamp,
    terms_accepted_at timestamp,
    analytics_consent boolean DEFAULT false NOT NULL,
    weekly_digest_enabled boolean DEFAULT true NOT NULL
);

